### ISSUE TITLE
Change ontology name to FIDO

### ISSUE THREAD

**Issue by grosscol** [Display-Lab/fido#144]
## Updates 
- [x] IRIs in the ontology
- [x] description in ontology
- [x] readme
- [x] project name (github url)
- [x] project description

## Github URL update consequence
After project name update, remote branches will have to be pointed at the new url.
```sh
git remote set-url origin https://github.com/Display-Lab/fido.git
``` 
OR for ssh based access
```sh
git remote set-url origin git@github.com:Display-Lab/fio.git
```

**Comment by grosscol** [comment]
I'd leave the IRI numbers the same and just change FIO -> FIDO.
I'll change the name of the repository after we merge the new branch.

**Comment by CooperStansbury** [comment]
Here's the whole protege error message:

`An exception has occurred when loading input file.
Message: Exception occurred while loading OBDA document: /Users/MILK/Desktop/Work/fio/src/ontology/fido-edit.obda

ERROR reading .obda file at line: 22 
MESSAGE: 1

###################################################
##    Debugging information (for the authors)    ##
###################################################

	at it.unibz.inf.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleOntologyLoadedAndReLoaded(OBDAModelManager.java:695)
	at it.unibz.inf.ontop.protege.core.OBDAModelManager$OBDAPluginOWLModelManagerListener.handleChange(OBDAModelManager.java:542)
	at org.protege.editor.owl.model.OWLModelManagerImpl.lambda$fireEvent$177(OWLModelManagerImpl.java:769)
	at org.protege.editor.owl.model.OWLModelManagerImpl$$Lambda$29/1556376365.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:749)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:719)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:109)
	at java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:184)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:229)
	at java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:227)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:227)
	at java.awt.Dialog.show(Dialog.java:1084)
	at java.awt.Component.show(Component.java:1654)
	at java.awt.Component.setVisible(Component.java:1606)
	at java.awt.Window.setVisible(Window.java:1014)
	at java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.protege.editor.owl.ui.util.ProgressDialog.lambda$setVisible$212(ProgressDialog.java:50)
	at org.protege.editor.owl.ui.util.ProgressDialog$$Lambda$102/333315979.run(Unknown Source)
	at org.protege.editor.owl.ui.util.ProgressDialog.setVisible(ProgressDialog.java:57)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntologyInOtherThread(OntologyLoader.java:65)
	at org.protege.editor.owl.model.io.OntologyLoader.loadOntology(OntologyLoader.java:53)
	at org.protege.editor.owl.model.OWLModelManagerImpl.loadOntologyFromPhysicalURI(OWLModelManagerImpl.java:277)
	at org.protege.editor.owl.OWLEditorKit.handleLoadFrom(OWLEditorKit.java:189)
	at org.protege.editor.owl.OWLEditorKit.handleLoadRecentRequest(OWLEditorKit.java:175)
	at org.protege.editor.core.ProtegeManager.openAndSetupRecentEditorKit(ProtegeManager.java:269)
	at org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.openInNewWorkspace(OpenRecentAction.java:90)
	at org.protege.editor.core.ui.util.UIUtil.openRequest(UIUtil.java:219)
	at org.protege.editor.core.ui.action.OpenRecentAction$RecentEditorKitAction.actionPerformed(OpenRecentAction.java:76)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2346)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at com.apple.laf.ScreenMenuItem.actionPerformed(ScreenMenuItem.java:125)
	at java.awt.MenuItem.processActionEvent(MenuItem.java:669)
	at java.awt.MenuItem.processEvent(MenuItem.java:628)
	at java.awt.MenuComponent.dispatchEventImpl(MenuComponent.java:351)
	at java.awt.MenuComponent.dispatchEvent(MenuComponent.java:339)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:754)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:702)
	at java.awt.EventQueue$3.run(EventQueue.java:696)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.awt.EventQueue$4.run(EventQueue.java:724)
	at java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:721)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)`

**Comment by CooperStansbury** [comment]
There is no description in the ontology currently.

**Comment by grosscol** [comment]
This looks like it's a requirement and consequence of the "Ontop" plugin.  If you're not using it, I suggest removing it.  Additionally, add .odba files to .gitignore as they're a development tooling artifact.

**Comment by grosscol** [comment]
If you're not using the Ontop plugin, I suggest removing it.  That plugin is what is throwing the error you're seeing.

The .odba file appears to be a data source descriptor used by that plugin.  So it can be removed from the repo and the path or pattern for the .odba file added to the list of files to ignore in .gitignore.

**Comment by CooperStansbury** [comment]
#148

**Comment by CooperStansbury** [comment]
@grosscol , the description of the project page still shows 'feedback intervention ontology.' As soon as this is updated this can be closed.

**Comment by grosscol** [comment]
Updated description.
